import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { readyTelegramDb } from '../packages/telegram/src/db.ts';
import { addTelegramSource, extractUrls, normalizeTelegramReference, rotateAllToken, rotateSourceToken,
  toggleTelegramSource, updateTelegramSettings } from '../packages/telegram/src/core.ts';
import { allRss, sourceRss } from '../packages/telegram/src/rss.ts';
import { renderSummary, summarizeJob, TELEGRAM_SUMMARY_SCHEMA } from '../packages/telegram/src/summarize.ts';
import { cleanupTelegram, retentionCutoff } from '../packages/telegram/src/maintenance.ts';
import { MockProvider } from '../packages/ai/src/providers/mock.ts';

const dir=mkdtempSync(join(tmpdir(),'brief-tg-')); const db=readyTelegramDb(join(dir,'telegram.db'));
let fail=0; const ok=(name:string,value:boolean)=>{if(!value)fail++;console.log(`  ${value?'✅':'❌'} ${name}`)};
const throws=(fn:()=>unknown)=>{try{fn();return false}catch{return true}};

console.log('Telegram 地址与 URL：\n');
ok('@username 归一化',normalizeTelegramReference('@HeZu_1').canonical==='@hezu_1');
ok('t.me/s 地址',normalizeTelegramReference('https://t.me/s/HeZu_1').canonical==='@hezu_1');
ok('私群消息链接映射稳定 chat_id',normalizeTelegramReference('t.me/c/12345/9').resolveAs===-1000000012345);
ok('邀请链接仅标记、不解析为公开用户名',normalizeTelegramReference('https://t.me/+secret').kind==='invite');
ok('拒绝查询参数',throws(()=>normalizeTelegramReference('https://t.me/hezu1?x=1')));
const urls=extractUrls('价格 11.30 和 0.85；看 Example.COM/a#part、https://EXAMPLE.com:443/a#x');
ok('排除小数价格',!urls.some(x=>x.includes('11.30')||x.includes('0.85')));
ok('规范化、片段移除并去重',urls.length===1&&urls[0]==='https://example.com/a');

console.log('\n来源状态与 token：\n');
const src=addTelegramSource(db,{reference:'t.me/hezu1',sourceType:'normal'});
ok('新增为 pending',src.status==='pending');
ok('pending 不能启用',throws(()=>toggleTelegramSource(db,src.id,true)));
db.prepare("UPDATE telegram_sources SET status='active',chat_id=-1001,enabled=1 WHERE id=?").run(src.id);
const dupe=addTelegramSource(db,{reference:'@hezu1',sourceType:'normal'});
ok('不同地址可待异步解析去重',dupe.status==='pending');
ok('普通来源 token 为 256 位',rotateSourceToken(db,src.id)?.length===64);
const urlSrc=addTelegramSource(db,{reference:'@urlchan',sourceType:'url'});
ok('URL 渠道拒绝 RSS token',throws(()=>rotateSourceToken(db,urlSrc.id)));
ok('停用不撤销 token',(()=>{const t=rotateSourceToken(db,src.id);toggleTelegramSource(db,src.id,false);return (db.prepare('SELECT rss_token FROM telegram_sources WHERE id=?').get(src.id) as any).rss_token===t})());

console.log('\n设置、RSS 与隔离：\n');
updateTelegramSettings(db,{timezone:'Asia/Shanghai',schedule:'22:00, 08:00,12:00',provider:'mock',model:'m',credentialRef:'OPENAI_COMPAT_API_KEY',promptRules:'关注发布'});
const settings=db.prepare('SELECT * FROM telegram_settings').get() as any;
ok('时段排序去重',settings.schedule_json==='["08:00","12:00","22:00"]');
ok('主要观点 Schema 最多允许一个段落',(TELEGRAM_SUMMARY_SCHEMA.properties.viewpoints as any).maxItems===1);
const token=rotateSourceToken(db,src.id)!; const allToken=rotateAllToken(db)!;
db.prepare("UPDATE telegram_sources SET status='active',enabled=1 WHERE id=?").run(src.id);
const now=new Date(), start=new Date(now.getTime()-3600000).toISOString(), end=now.toISOString();
const job=db.prepare(`INSERT INTO telegram_summary_jobs(source_id,window_start,window_end,input_hash,provider,model,prompt_version,status,created_at,updated_at) VALUES(?,?,?,'h','mock','m',1,'completed',?,?)`).run(src.id,start,end,end,end);
const html=renderSummary({topics:['<主题>'],important:['讨论中，有人提出A&B（消息 11194397, 11194405）。'],viewpoints:['有人提出套餐价格偏高。','讨论中有人认为按量计费更灵活。','群友表示年付适合长期使用（消息 ID：11194397）'],sources:[{messageId:7,time:start}],uncertainty:['消息中提到仍需核实。']});
db.prepare(`INSERT INTO telegram_summaries(job_id,source_id,window_start,window_end,title,summary_json,rendered_html,created_at,expires_at) VALUES(?,?,?,?,?,?,?,?,?)`).run(job.lastInsertRowid,src.id,start,end,'x < y','{}',html,end,new Date(now.getTime()+86400000).toISOString());
ok('RSS XML 转义',sourceRss(db,token,'https://brief.test')!.includes('&amp;lt;主题&amp;gt;'));
ok('新总结不渲染消息来源结构',!html.includes('消息来源')&&!html.includes(`#7 · ${start}`));
ok('新总结正文清理内嵌消息编号',html.includes('A&amp;B。')&&!html.includes('11194397')&&!html.includes('11194405'));
ok('展示字段移除句首和句中引导语',html.includes('<h2>主要观点</h2><p>套餐价格偏高。 讨论中按量计费更灵活。 年付适合长期使用</p>')&&!html.includes('有人')&&!html.includes('群友')&&!html.includes('消息中提到'));
db.prepare('UPDATE telegram_summaries SET rendered_html=? WHERE job_id=?').run(`<h2>主题</h2><ul><li>测试</li></ul><h2>重要信息</h2><ul><li>有人提出价格变化。</li></ul><h2>主要观点</h2><ul><li>有人提出套餐价格偏高。</li><li>有人认为按量计费更灵活。</li></ul><h2>不确定信息</h2><ul><li>消息中提到仍需核实。</li></ul><h2>消息来源</h2><ul><li>#7 · ${start}</li></ul><p>历史文本（消息 11194397、11194405）。</p>`,job.lastInsertRowid);
const historicalFeed=sourceRss(db,token,'https://brief.test')!;
ok('RSS 隐藏历史总结的消息来源结构',!historicalFeed.includes('消息来源')&&!historicalFeed.includes(`#7 · ${start}`));
ok('RSS 清理历史总结内嵌消息编号',historicalFeed.includes('历史文本。')&&!historicalFeed.includes('11194397')&&!historicalFeed.includes('11194405'));
ok('RSS 将历史观点列表合并为一个段落',historicalFeed.includes('&lt;h2&gt;主要观点&lt;/h2&gt;&lt;p&gt;套餐价格偏高。 按量计费更灵活。&lt;/p&gt;')&&!historicalFeed.includes('有人'));
ok('RSS 清理所有历史展示字段的引导语',!historicalFeed.includes('消息中提到')&&!historicalFeed.includes('群友'));
const dateParts=Object.fromEntries(new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit'}).formatToParts(new Date(end)).filter(x=>x.type!=='literal').map(x=>[x.type,x.value]));
const mmdd=`${dateParts.month}-${dateParts.day}`;
db.prepare('UPDATE telegram_sources SET title=? WHERE id=?').run('[合租社群]Netflix|YouTube|Spotify|office365|Hbo|Surge|美剧|等音乐影视聊天机场电影盒子软路由',src.id);
ok('指定群组 RSS 标题精简且不含年份',sourceRss(db,token,'https://brief.test')!.includes(`<title>合租社群 ${mmdd}</title>`));
db.prepare('UPDATE telegram_sources SET title=? WHERE id=?').run('其他群组',src.id);
ok('其他群组 RSS 标题为名称加月日',sourceRss(db,token,'https://brief.test')!.includes(`<title>其他群组 ${mmdd}</title>`));
ok('汇总 feed 包含启用普通来源',allRss(db,allToken,'https://brief.test')!.includes('telegram:'));
db.prepare("UPDATE telegram_sources SET enabled=1,status='active',chat_id=-1002 WHERE id=?").run(urlSrc.id);
ok('汇总 feed 不包含 URL 渠道',!allRss(db,allToken,'https://brief.test')!.includes(`telegram:${urlSrc.id}:`));
const old=token;rotateSourceToken(db,src.id);ok('重置立即撤销旧 token',sourceRss(db,old,'')===null);
ok('数据表不为 URL 渠道提供正文列',!db.prepare("PRAGMA table_info(telegram_urls)").all().some((x:any)=>['text','sender_id','message_id'].includes(x.name)));

console.log('\n总结幂等、故障隔离与保留：\n');
ok('6 个自然日从业务日零点计算',retentionCutoff(new Date('2026-09-07T10:00:00Z'),'Asia/Shanghai',6).toISOString()==='2026-09-01T16:00:00.000Z');
const start2=new Date(now.getTime()+1000).toISOString(),end2=new Date(now.getTime()+3601000).toISOString();
db.prepare(`INSERT INTO telegram_messages(source_id,chat_id,message_id,sent_at,text,content_hash,collected_at) VALUES(?,?,?,?,?,?,?)`).run(src.id,-1001,7,start2,'仅供测试的消息','h',start2);
const j2=db.prepare(`INSERT INTO telegram_summary_jobs(source_id,window_start,window_end,input_hash,provider,model,prompt_version,status,created_at,updated_at) VALUES(?,?,?,'','mock','m',1,'pending',?,?)`).run(src.id,start2,end2,start2,start2);
ok('单窗口结构化总结成功',await summarizeJob(db,Number(j2.lastInsertRowid),{provider:'mock',model:'m',promptRules:'',promptVersion:1,summaryRetentionDays:30},new MockProvider({provider:'mock',model:'m'})));
ok('完成任务不可被规则变化重写',!(await summarizeJob(db,Number(j2.lastInsertRowid),{provider:'mock',model:'m',promptRules:'变化',promptVersion:2,summaryRetentionDays:30},new MockProvider({provider:'mock',model:'m'}))));
const failedStart=new Date(now.getTime()+7201000).toISOString(),failedEnd=new Date(now.getTime()+10801000).toISOString();
const jf=db.prepare(`INSERT INTO telegram_summary_jobs(source_id,window_start,window_end,input_hash,provider,model,prompt_version,status,created_at,updated_at) VALUES(?,?,?,'','mock','m',1,'pending',?,?)`).run(src.id,failedStart,failedEnd,start2,start2);
db.prepare(`INSERT INTO telegram_messages(source_id,chat_id,message_id,sent_at,text,content_hash,collected_at) VALUES(?,?,?,?,?,?,?)`).run(src.id,-1001,8,failedStart,'失败隔离测试','h2',failedStart);
const bad={name:'mock',model:'m',strictness:'strict',complete:async()=>{throw new Error('isolated')}} as any;
ok('单群失败返回且不抛出阻塞其他群组',!(await summarizeJob(db,Number(jf.lastInsertRowid),{provider:'mock',model:'m',promptRules:'',promptVersion:1,summaryRetentionDays:30},bad)));
ok('失败任务保留有限重试',(db.prepare('SELECT status,next_attempt_at FROM telegram_summary_jobs WHERE id=?').get(jf.lastInsertRowid) as any).status==='failed');
db.prepare(`INSERT INTO telegram_urls(normalized_url,first_source_id,last_source_id,first_discovered_at,last_discovered_at,expires_at) VALUES('https://expired.test/',?,?,?,?,?)`).run(urlSrc.id,urlSrc.id,start,start,new Date(now.getTime()-1).toISOString());
const cleaned=cleanupTelegram(db,new Date(now.getTime()+86400000));
ok('URL 按最后发现后的过期时间清理',cleaned.urls===1);
ok('integrity_check=ok',db.pragma('integrity_check',{simple:true})==='ok');
db.close();rmSync(dir,{recursive:true,force:true});
console.log(fail?`\n❌ ${fail} 项失败`:'\n✅ 全部通过');process.exit(fail?1:0);
